============================= test session starts ==============================
platform linux -- Python 3.11.8, pytest-8.0.0, pluggy-1.4.0
rootdir: /home/runner/work/Assessment-Backend-Week-1/Assessment-Backend-Week-1
[]
collected 85 items

days_api/test_api.py ................................................... [ 60%]
.........                                                                [ 70%]
days_api/test_date_functions.py .........................                [100%]

============================== 85 passed in 0.21s ==============================
************* Module app
days_api/app.py:43:8: W0702: No exception type(s) specified (bare-except)
days_api/app.py:58:8: W0702: No exception type(s) specified (bare-except)
days_api/app.py:67:4: W0603: Using the global statement (global-statement)
************* Module date_functions
days_api/date_functions.py:14:8: W0707: Consider explicitly re-raising using 'except ValueError as exc' and 'raise ValueError('Unable to convert value to datetime.') from exc' (raise-missing-from)

------------------------------------------------------------------
Your code has been rated at 9.82/10 (previous run: 9.82/10, +0.00)

